Controllers/Belt2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using CSBelt2.Models;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace CSBelt2.Controllers
{
    public class Belt2Controller : Controller
    {
        private Belt2Context _context;   

        public Belt2Controller(Belt2Context context)
        {
            _context = context;
        }

        [HttpGet, Route("brightideas")]
        public IActionResult Dashboard()
        {
            if(IsLoggedIn())
            {
                GetUserFromSession();
                IdeasBundle IdeasFormsBundle = new IdeasBundle
                {
                    IdeaModel = new Idea(),
                    AllIdeas = _context.ideas.Include(idea => idea.Poster).Include(i => i.UsersWhoLiked).ThenInclude(m => m.User).OrderByDescending(idea => idea.UsersWhoLiked.Count).ToList()
                };
                
                return View("Dashboard", IdeasFormsBundle);
            }
            return RedirectToAction("Login", "Users");
        }

        [HttpPost, Route("brightideas")]
        public IActionResult CreateIdea(IdeasBundle model)
        {
            if(IsLoggedIn())
            {
                GetUserFromSession();
                int userId = (int)TempData["UserId"];
                if(ModelState.IsValid)
                {
                    User user = _context.users.SingleOrDefault(u => u.UserId == userId);
                    model.IdeaModel.Poster = user;
                    model.IdeaModel.PosterId = userId;
                    _context.ideas.Add(model.IdeaModel);
                    _context.SaveChanges();
                    return RedirectToAction("Dashboard");
                }
                model.AllIdeas = _context.ideas.Include(idea => idea.Poster).Include(i => i.UsersWhoLiked).ThenInclude(m => m.User).OrderByDescending(idea => idea.UsersWhoLiked.Count).ToList();
                return View("Dashboard", model);
            }
            return RedirectToAction("Login", "Users");
        }

        [HttpGet, Route("delete/{ideaId}")]
        public IActionResult Delete(int ideaId)
        {
            if(IsLoggedIn())
            {
                GetUserFromSession();
                Idea idea = _context.ideas.SingleOrDefault(i => i.IdeaId == ideaId);
                if (idea.PosterId == (int)TempData["UserId"])
                {
                    // CASCADE property on Idea in db
                    _context.ideas.Remove(idea);
                    _context.SaveChanges();
                }
                return RedirectToAction("Dashboard");
            }
            return RedirectToAction("Login", "Users");
        }
        public void GetUserFromSession()
        {
            TempData["UserId"] = (int?)HttpContext.Session.GetInt32("UserId");
            TempData["UserName"] = HttpContext.Session.GetString("UserName");
            TempData["Alias"] = HttpContext.Session.GetString("Alias");
        }

        public bool IsLoggedIn()
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            return (UserId != null); // evaluates the boolean like an if statement
        }

        [HttpGet, Route("like/{ideaId}")]
        public IActionResult Like(int ideaId)
        {
            if(IsLoggedIn())
            {
                GetUserFromSession();
                int userId = (int)TempData["UserId"];
                User user = _context.users.SingleOrDefault(u => u.UserId == userId);
                // LikesMap like = _context.likesmap.Where(m => m.IdeaId == ideaId).SingleOrDefault(map => map.UserId == userId);
                _context.likesmap.Add(new LikesMap{ IdeaId = ideaId, UserId = userId });
                _context.SaveChanges();
                return RedirectToAction("Dashboard");
            }
            return RedirectToAction("Dashboard");
        }

        [HttpGet, Route("brightideas/{ideaId}")]
        public IActionResult LikeStatus(int ideaId)
        {
            if(IsLoggedIn())
            {
                GetUserFromSession();
                var distinctUsersWhoLiked = new Dictionary<string, User>();
                Idea idea = _context.ideas.Include(idear => idear.Poster).Include(i => i.UsersWhoLiked).ThenInclude(m => m.User).Distinct().SingleOrDefault(idear => idear.IdeaId == ideaId);

                foreach(var user in idea.UsersWhoLiked)
                {
                    if(!distinctUsersWhoLiked.ContainsKey(user.User.Name))
                    {
                        distinctUsersWhoLiked.Add(user.User.Name, user.User);
                    }
                }
                ViewBag.DistinctUsers = distinctUsersWhoLiked;
                return View("LikeStatus", idea);
            }
            return RedirectToAction("Login", "Users");
        }

        [HttpGet, Route("users/{userId}")]
        public IActionResult Profile(int userId)
        {
            if(IsLoggedIn())
            {
                GetUserFromSession();
                // var user = _context.users.Include(l => l.LikedPosts).SingleOrDefault(u => u.UserId == (int)TempData["UserId"]);
                var map = _context.likesmap.Where(m => m.UserId == userId).ToList();
                var postsCount = _context.ideas.Where(i => i.PosterId == userId).ToList().Count;
                TempData["PostCount"] = postsCount;

                UserBundle UserProfileBundle = new UserBundle()
                {
                    UserModel = _context.users.SingleOrDefault(u => u.UserId == userId),
                    AllLikes = map
                };
                return View("Profile", UserProfileBundle);
            }
            return RedirectToAction("Login", "Users");
        }
    }
}

Views/Belt2/Dashboard.cshtml
@model CSBelt2.Models.IdeasBundle

<div class="wrapper">
    <div class="header">
        <h1>Hi @TempData["Alias"]</h1>
        <a asp-controller="Users" asp-action="Logout">Log off</a>
    </div>
    <div class="ideaFormContainer">
        <form asp-controller="Belt2" asp-action="CreateIdea" method="POST">
            <label asp-for="@Model.IdeaModel.Description"></label>
            <input asp-for="@Model.IdeaModel.Description"><br>
            <span asp-validation-for="@Model.IdeaModel.Description"></span><br>

            <button type="submit">Idea!</button>
        </form>
    </div>
    <hr>
    <div class="allIdeas">
        @foreach(var idea in @Model.AllIdeas)
        {
            <div class="ideaCard">
                <p><a asp-controller="Belt2" asp-action="Profile" asp-route-userId="@idea.PosterId" class="alias">@idea.Poster.Alias</a> says: </p>
                <div class="description">@idea.Description</div>
                <a asp-controller="Belt2" asp-action="Like" asp-route-ideaId="@idea.IdeaId">Like</a> |
                <a asp-controller="Belt2" asp-action="LikeStatus" asp-route-ideaId="@idea.IdeaId">@idea.UsersWhoLiked.Count people</a> like this --sort of 
                @if(@idea.PosterId == (int)TempData["UserId"])
                {
                    <span>| <a asp-controller="Belt2" asp-action="Delete" asp-route-ideaId="@idea.IdeaId">Delete</a></span>
                }
                
            </div>
        }
    </div>
</div>

Views/Belt2/LikeStatus.cshtml
@model CSBelt2.Models.Idea

<div class="statusContainer">
    <div class="header">
        <a asp-controller="Belt2" asp-action="Dashboard">Bright Ideas</a>
        <a asp-controller="Users" asp-action="Logout">Log off</a>
    </div>
    <hr>
    <div class="likeInfoContainer">
        <p><a asp-controller="Belt2" asp-action="Profile" asp-route-userId="@Model.PosterId">@Model.Poster.Alias</a> says: </p>
        <div class="ideaContainer">
            @Model.Description
        </div>

        <h4>People who liked this post:</h4>
        <table>
            <thead>
                <th>Alias</th>
                <th>Name</th>
            </thead>
            <tbody>
                @foreach(KeyValuePair<string, User> user in ViewBag.DistinctUsers)
                {
                    <tr>
                        <td><a asp-controller="Belt2" asp-action="Profile" asp-route-userId="@user.Value.UserId">@user.Value.Alias</a></td>
                        <td>@user.Value.Name</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Belt2/Profile.cshtml
@model CSBelt2.Models.UserBundle

<div class="profileWrapper">
    <div class="header">
        <a asp-controller="Belt2" asp-action="Dashboard">Bright Ideas</a>
        <a asp-controller="Users" asp-action="Logout">Log off</a>
    </div>
    <hr>
    <div class="profile">
        <h3>Name: @Model.UserModel.Name</h3>
        <h3>Alias: @Model.UserModel.Alias</h3>
        <h3>Email: @Model.UserModel.Email</h3>
        <hr>
        <h3>Total Number of Posts: @TempData["PostCount"]</h3>
        <h3>Total Number of Likes: @Model.AllLikes.Count</h3>
    </div>
</div>